sylius_grid:
    grids:
        app_admin_companies:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Companies\Companies
            fields:
                name_entreprise:
                    type: string
                email:
                    type: string

            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        app_admin_contact:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Contact\Contact
            fields:
                firstname_contact:
                    type: string
                lastname_contact:
                    type: string
                email:
                    type: string
                
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        app_admin_task:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Task\Task
            fields:
                name_task:
                    type: string
                description:
                    type: string
                status:
                    type: string
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete
        app_admin_project:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Project\Project
            fields:
                name_project:
                    type: string

            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

                        
