sylius_grid:
    grids:
        app_admin_companies:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Companies
            fields:
                name_entreprise:
                    type: string
                email:
                    type: string
                phone:
                    type: int
                date_creation:
                    type: date
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

        app_admin_contact:
            driver:
                name: doctrine/orm
                options:
                    class: App\Entity\Contact
            fields:
                firstname_contact:
                    type: string
                lastname_contact:
                    type: string
                email:
                    type: string
                phone:
                    type: int
            actions:
                main:
                    create:
                        type: create
                item:
                    update:
                        type: update
                    delete:
                        type: delete

                        
