sylius_resource:
    resources:
        app.companies:
            classes:
                model: App\Entity\Companies
        app.contact:
            classes:
                model: App\Entity\Contact
        app.task:
            classes:
                model: App\Entity\Task