app_companies:
    resource: |
        alias: app.companies
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: app_admin_companies
        redirect: index
    type: sylius.resource
    prefix: admin
app_contact:
    resource: |
        alias: app.contact
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: app_admin_contact
        redirect: index
    type: sylius.resource
    prefix: admin
app_task:
    resource: |
        alias: app.task
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: app_admin_task
        redirect: index
    type: sylius.resource
    prefix: admin
app_project:
    resource: |
        alias: app.project
        section: admin
        templates: SyliusAdminBundle:Crud
        grid: app_admin_project
        redirect: index
    type: sylius.resource
    prefix: admin